#-  Travis CI configuration file

#-  .travis.yml ~~
#                                                       ~~ (c) SRW, 15 Jul 2013
#                                                   ~~ last updated 16 Jul 2013

language: node_js

node_js:
    -   "0.10"

#-  vim:set syntax=yaml:
